server:
  port: 5050
  
eureka:
  instance:
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 12
  client:
    registry-fetch-interval-seconds: 10 #eureka client刷新本地缓存时间，默认30
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
 
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #netty 路由过滤器，http或https开头
      - id: api-a-route
        uri: http://localhost:8080
        predicates:
        - Path=/api-a/**
        filters:
          #转发请求时去掉1级前缀
        - StripPrefix=1
        #LoadBalancerClient负载均衡过滤器（整合eureka注册中心），lb开头
      - id: api-aa-route
        uri: lb://hello-service
        predicates:
        - Path=/api-aa/**
        filters:
        #转发请求时去掉1级前缀
        - StripPrefix=1